const mongoose = require('mongoose');

const librarySchema = new mongoose.Schema({
    libraryName: {
        type: String,
        required: true
    },
    location: {
        type: String,
        required: true
    },
    libraryAdminEmail: {
        type: String,
        required: true,
        unique: true,
    },
    isFirstLogin: {
        type: Boolean,
        default: true
    },
    autoGeneratedPassword: {
        type: String,
        required: true
    },
});

const Library = mongoose.model('Library', librarySchema);

module.exports = Library;
