const mongoose = require('mongoose');

const subscriptionSchema = new mongoose.Schema({
    organizationName: {
        type: String,
        required: true
    },
    location: {
        type: String,
        required: true
    },
    adminEmail: {
        type: String,
        required: true,
        unique: true,
    },
    expiryDate: {
        type: Date,
        required: true
    },
    autoGeneratedPassword: {
        type: String,
        required: true
    },
    isExpired: {
        type: Boolean,
        default: false
    },
    isFirstLogin: {
        type: Boolean,
        default: true
    },
});

const Subscription = mongoose.model('Subscription', subscriptionSchema);

module.exports = Subscription;
